### ISSUE TITLE
Pokus o založení nové aplikace skončí chybou

### ISSUE THREAD

**Issue by fosil** [rosti-cz/rostictl#2]
Prostředí: MacOS 12.1 (ale i 12.0.1)

Zavolání příkazu: rostictl up

Výpis (anonymizovaný):
You have access to multiple companies, pick one of the companies below and use -c COMPANY_ID flag to call this command.

      ID  Company name
  ------  ------------
      xx  xxxxxx
     xxx  xxxxxx
     xxx  xxxxxx
     xxx  xxxxxx
     xxx  xxxxxx
     xxx  xxxxxx
     xxx  xxxxxx
    xxxx  xxxxxx
    xxxx  xxxxxx
    xxxx  xxxxxx
    xxxx  xxxxxx
    xxxx  xxxxxx
    xxxx  xxxxxx

.. loading list of available plans
.. loading list of available runtimes
.. creating a new application XXXX 
Response body: [1111011 100010 1101101 1100101 1110011 1110011 1100001 1100111 1100101 100010 111010 100010 1010100 1101000 1100101 100000 1100011 1101111 1101101 1110000 1100001 1101110 1111001 100000 1101000 1100001 1110011 100000 1101110 1101111 1110100 100000 1100010 1100101 1100101 1101110 100000 1100110 1101111 1110101 1101110 1100100 101110 100010 101100 100010 1100101 1110010 1110010 1101111 1110010 1110011 100010 111010 1011011 1011101 1111101]2021/12/15 16:23:32 problem while decoding error message: json: cannot unmarshal array into Go struct field ErrorResponse.errors of type map[string]interface {}

Výstup po zadání COMPANY_ID:
.. loading Rostifile
.. loading state file
.. loading list of your companies
.. loading list of available plans
.. loading list of available runtimes
.. creating a new application Inzerce 
.. checking if SSH daemon is ready
2021/12/15 16:26:42 SSH daemon has not started in time

Aplikace se zobrazí v aminu na rosti.cz, ale SSH prozradí, že není nastavena ani technologie

Díky!

**Comment by petrvacha** [comment]
Mám podobný problém. 
```% rostictl up                      
.. loading Rostifile
.. loading state file
.. loading list of your companies
.. loading list of available plans
.. loading list of available runtimes
.. loading current state of the application
.. updating existing application XXXX 
.. checking if SSH daemon is ready
2022/01/26 22:46:15 SSH daemon has not started in time

Co s tím?

**Comment by by-cx** [comment]
S @petrvacha jsme byli schopni oddebugovat co se tam děje. V jeho případě byl SSH klíč chráněný heslem. S tím už se dá něco dělat, takže oprava bude brzo. Kromě toho, když nedojde k připojení, tak se vypíše chyba z posledního pokusu, takže debug by měl být příště mnohem pohodlnější.

**Comment by by-cx** [comment]
Opraveno ve verzi v6.

https://github.com/rosti-cz/rostictl/releases/tag/v6
