### ISSUE TITLE
Invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by vaclavpavek** [rosti-cz/rostictl#4]
**Version:** 0.6

**Description:** files have not been transferred to the server

**Rostifile**
```
name: test
technology: php
https: false
source_path: .
processes:
- name: app
  command: /srv/bin/primary_tech/php-fpm -F -O -g /srv/run/php-fpm.pid -y /srv/conf/php-fpm/php-fpm.conf
```

**Deploy APP**
![obrazek](https://user-images.githubusercontent.com/695438/165380728-ab268d52-5bf7-4c8b-8f0e-1c3e0637f8a7.png)

**Comment by by-cx** [comment]
@vaclavpavek Hi, the problem has been fixed.
